### ISSUE TITLE
Distribute via krew?

### ISSUE THREAD

**Issue by corneliusweig** [adamglt/fwd#1]
:wave: Hello, maintainer of the kubectl plugin manager [krew](https://github.com/kubernetes-sigs/krew) here.

What do you think about making your plugin available via krew? You would benefit from

- Greater visibility due krew's large user basis.
- Easier installs.
- Seamless upgrades for new plugin versions.

Krew already has over [60 plugins](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md) and more are coming in. See our [development guide](https://github.com/GoogleContainerTools/krew/blob/master/docs/DEVELOPER_GUIDE.md) if you're interested. I can't promise that your plugin can keep its name, though. Please see our [naming guide](https://github.com/kubernetes-sigs/krew/blob/master/docs/NAMING_GUIDE.md) for that topic.

**Comment by adamglt** [comment]
Hey - I would like to, but unfortunately fwd requires sudo and makes (temporary) changes to the client machine (/etc/hosts and ifconfig).

I think that sort of behavior isn't encouraged for regular kubectl plugins - not sure though.

**Comment by corneliusweig** [comment]
I see. That is indeed a bit peculiar for a plugin. There are a few which require privileged containers, but none that needs to run as root.

Do you think you could re-architect your plugin by relying on some local DNS service instead of editing `/etc/hosts`?

**Comment by adamglt** [comment]
Yeah, a local DNS could replace the loopback + /etc/hosts tricks, but modifying the resolver to use that nameserver would require root (or manual user interaction).

Since this whole thing is a hack for quick and dirty cluster access I can't really think of a standalone tool that could provide the current functionality with zero user interaction.

**Comment by corneliusweig** [comment]
Ok, thanks for explaining. Then let's close this for now.

If I find that we are taking in plugins which only run as root, we can as well re-visit this.
