### ISSUE TITLE
Renaming/aliasing services

### ISSUE THREAD

**Issue by aakarim** [adamglt/fwd#3]
Hi, I'm loving this tool. One thing would make it better for me is aliasing or renaming services. 

Some services as default, especially when run by operators, have exceptionally long names that are a pain to type out every time. This makes local development and utilisation of APIs very painful. 

A simple solution would be aliasing of services, would this be possible?

**Comment by adamglt** [comment]
Sure, example added to readme.

**Comment by aakarim** [comment]
Thank you for solving this so quickly.
